# Generated by Django 4.2.6 on 2024-02-13 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Importaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Importaciones.producto'),
        ),
    ]
